### ISSUE TITLE
Finalize labels and colors

### ISSUE THREAD

**Issue by mccalluc** [mccalluc/github-utils#1]
@ngehlenborg : I think you had the strongest opinion about the issue labels: Does this work?
```
new_labels = {
    # Type
    'Bug': 'db2d1a',
    'Technical Debt': '9c2011',
    'Question': '76429a',
    'Enhancement': '09457f',
    'Feature': '1779dc',
    # Severity
    'Critical': 'dc6b24',
    'Important': 'f28f2e'
}
```
Github just sorts alphabetically, so wondering if it would make sense to use numbers in severity labels so they'd be segregated? I've run it on phovea.github.io, and this is what it looks like:
<img width="138" alt="screen shot 2016-11-17 at 3 42 42 pm" src="https://cloud.githubusercontent.com/assets/730388/20406793/b9afe436-acdc-11e6-8efe-000cf7a63ca4.png">

**Comment by mccalluc** [comment]
@ngehlenborg : Ping. I think you cared most strongly about this, so could you look at https://github.com/phovea/phovea.github.io/labels, tweak it as needed, and then I'll apply it to all repos? 

- Three facets: severity, type, and layer.
- (Component isn't applicable because of our fine-grained repos.)
- Naming conventions segregate the facets in an alphabetically sorted list.
- Distinct color schemes for each facet.

<img width="104" alt="screen shot 2016-11-27 at 11 28 16 am" src="https://cloud.githubusercontent.com/assets/730388/20649776/d8cdd4b2-b494-11e6-9008-ec05af028c61.png">

**Comment by ngehlenborg** [comment]
Hey @mccalluc - what do you think about this option:

![image](https://cloud.githubusercontent.com/assets/1216518/20659468/c6df6748-b511-11e6-9621-b986ec41674c.png)

![image](https://cloud.githubusercontent.com/assets/1216518/20659477/da60659c-b511-11e6-8477-b850b571511b.png)

**Comment by mccalluc** [comment]
Will do. Thanks!

**Comment by mccalluc** [comment]
Ok: Updated script and ran on phovea/* ... For caleydo/* the costs seem higher / benefits lower to do something across all repos, so I'll put a note on Slack and close this issue for now.
