### ISSUE TITLE
Just reference in prose, or does it need to be automatic?

### ISSUE THREAD

**Issue by mccalluc** [mccalluc/github-utils#2]
@sgratzl : I had been thinking that we'd just reference this script in the documentation, but from something you said this morning I was wondering if you thought it should be run automatically? If I'm imagining that, sorry for the bother: I think it's fine to run by hand.

**Comment by sgratzl** [comment]
I would love to run this and similar scripts on some kind of server. Such that if you create a new repository, you just have to enter the repository name, press a button and it will be initialized. 

I previously used a configurable jenkins job for similar tasks. We could also think about creating a simple heroku app. There is a general CaleydoJenkins account that is part of the bot team that we could use as the user account.
